# Generated by Django 5.2.5 on 2025-09-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('depertment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('head_of_department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=100)),
                ('instructor_id', models.IntegerField()),
                ('day', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('date_issued', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='testingdatabase',
            name='first_name',
            field=models.DateTimeField(),
        ),
    ]
