# Generated by Django 5.2.5 on 2025-09-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_course_department_schedule_student_transcript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
