# Generated by Django 5.2.5 on 2025-09-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0003_alter_department_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='date_issued',
            field=models.CharField(max_length=100),
        ),
    ]
