# Generated by Django 5.2.5 on 2025-09-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0004_alter_schedule_time_alter_transcript_date_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.CharField(max_length=100),
        ),
    ]
