# Generated by Django 5.2.5 on 2025-09-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0005_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
