# Generated by Django 5.2.5 on 2025-09-09 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0008_alter_schedule_day_alter_schedule_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
