# Generated by Django 5.2.5 on 2025-09-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0009_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=100)),
                ('instructor_id', models.IntegerField()),
                ('day', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
