# Generated by Django 5.2.5 on 2025-09-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0010_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(),
        ),
    ]
