# Generated by Django 5.2.5 on 2025-09-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0011_alter_schedule_day_alter_schedule_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AlterField(
            model_name='testingdatabase',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
