# Generated by Django 5.2.5 on 2025-09-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0012_delete_schedule_alter_testingdatabase_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=100)),
                ('instructor_id', models.IntegerField()),
                ('day', models.CharField()),
                ('time', models.CharField()),
            ],
        ),
    ]
